"""Geometry constants aligned with Function_Ref/auto_parking_proposal.py."""

SUV_BLOCK = "SUV_BLOCK"
SEDAN_BLOCK = "SEDAN_BLOCK"
GROUND_BLOCK = "GROUND_LEVEL_BLOCK"
MACHINE_ROOM_BLOCK = "MACHINE_ROOM_BLOCK"
PLACE_HOLDER = "PLACE_HOLDER"
PARKING_BLOCK = "PARKING_BLOCK"

SUV_SPACING = 2100
SEDAN_SPACING = 1800
GROUND_BLOCK_HEIGHT = 6913
SUV_BLOCK_HEIGHT = 2100
SEDAN_BLOCK_HEIGHT = 1800

PARKING_SCALE_X = 7000.0 / 6700.0

SUV_START_X = 11600
SUV_START_Y = 7400
LABEL_LINE_LENGTH = 2500
LABEL_TEXT_HEIGHT = 400

DIM_Y_START = 3912.51
DIMENSION_OFFSET_X = -3150

# Default dynamic-style block parameters (former Excel DYNAMIC BLOCK PARMATER sheet)
DEFAULT_BLOCK_PARAMS: dict[str, dict[str, float | None]] = {
    "PALLET_DYN_BLOCK": {"X": 100.0, "Y": 200.0},
    "COUNTER_WEIGHT_DYN_BLOCK": {"X": 150.0, "Y": None},
    "TRANSPORTER_DYN_BLOCK": {"X": None, "Y": 300.0},
    "RCC_BRACKET_DYN_BLOCK": {"X": 120.0, "Y": None},
    "RCC_DYN_BLOCK": {"X": 100.0, "Y": 100.0},
}
